# Universal $\mathcal{P}_1(\mathbb{R})$-Deep Neural Model (Type A)
---

---
# Training Algorithm:
---
## 1) Generate Data:
Generates the empirical measure $\sum_{n=1}^N \delta_{X_T(\omega_n)}$ of $X_T$ conditional on $X_0=x_0\in \mathbb{R}$ *($x_0$ and $T>0$ are user-provided)* by simulating from:
$$ 
X_T = x + \int_0^T \alpha(s,x)ds + \int_0^T\beta(s,x)dW_s.
$$

## 2) Get "Sample Barycenters":
Let $\{\mu_n\}_{n=1}^N\subset\mathcal{P}_1(\mathbb{R}^d)$.  Then, the *sample barycenter* is defined by:
1. $\mathcal{M}^{(0)}\triangleq \left\{\hat{\mu}_n\right\}_{n=1}^N$,
2. For $1\leq n\leq \mbox{N sample barycenters}$: 
    - $
\mu^{\star}\in \underset{\tilde{\mu}\in \mathcal{M}^{(n)}}{\operatorname{argmin}}\, \sum_{n=1}^N \mathcal{W}_1\left(\mu^{\star},\mu_n\right),
$
    - $\mathcal{M}^{(n)}\triangleq \mathcal{M}^{(n-1)} - \{\mu^{\star}\},$
*i.e., the closest generated measure form the random sample to all other elements of the random sample.*

---
**Note:** *We simplify the computational burden of getting the correct classes by putting this right into this next loop.*

## 3) Train Deep Classifier:
$\hat{f}\in \operatorname{argmin}_{f \in \mathcal{NN}_{d:N}^{\star}} 
\sum_{x \in \mathbb{X}}
\, 
\mathbb{H}
\left(
    \operatorname{Softmax}_N\circ f(x)_n| I\left\{W_1(\hat{\mu}_n,\mu_x),\inf_{m\leq N} W_1(\hat{\mu}_m,\mu_x)\right\}
\right);
$
where $\mathbb{H}$ is the categorical cross-entropy.  

---
---
---
## Notes - Why the procedure is so computationally efficient?
---
 - The sample barycenters do not require us to solve for any new Wasserstein-1 Barycenters; which is much more computationally costly,
 - Our training procedure never back-propages through $\mathcal{W}_1$ since steps 2 and 3 are full-decoupled.  Therefore, training our deep classifier is (comparatively) cheap since it takes values in the standard $N$-simplex.

---

## Meta-Parameters

### Visualization

In [1]:
# How many random polulations to visualize:
Visualization_Size = 4

### Quantization
*This hyperparameter describes the proportion of the data used as sample-barycenters.*

In [2]:
Quantization_Proportion = 1

### Simulation

In [3]:
## Monte-Carlo
N_Euler_Maruyama_Steps = 2
N_Monte_Carlo_Samples = 100

N_Monte_Carlo_Samples_Test = 10 # How many MC-samples to draw from test-set?
T_end = 1
Direct_Sampling = True #This hyperparameter determines if we use a Euler-Maryama scheme or if we use something else.  

## Grid
N_Grid_Finess = 20
Max_Grid = 1

**Note**: Setting *N_Quantizers_to_parameterize* prevents any barycenters and sub-sampling.

#### Mode: Code-Testin Parameter(s)

In [4]:
trial_run = True

### Meta-parameters

In [5]:
# Test-size Ratio
test_size_ratio = .75

## SDE Simulation Hyper-Parameter(s)

### Drift

In [6]:
def alpha(t,x):
    return np.sin(math.pi*x)

### Volatility

In [7]:
def beta(t,x):
    return 1+ (x**2)

---
# Run Backend:
*Runs the backend with these pre-specified hyperparameters*.

In [8]:
# Use is user prefers GUI
# %run Universal_Processes_Trainer_BACKEND.ipynb
# Use for faster/shorter execution times (note: more amenable to terminal)
exec(open('Universal_Processes_Trainer_BACKEND.py').read())

Using TensorFlow backend.
100%|██████████| 20/20 [00:00<00:00, 11621.79it/s]

Deep Feature Builder - Ready
Deep Classifier - Ready
• Grid Instances:  20 and : 15  Testing instances.
• 20  Centers will be produced; from a total datasize of:  20 !  (That's  1  percent).
• Each Wasserstein-1 Ball should contain:  1 elements from the training set.
Current Monte-Carlo Step:
Using Euler-Maruyama distritization + Monte-Carlo Sampling.
Done Simulation Step (Train Set)
Done Simulation Step (Test Set)
😚  Begin Building Distance Matrix  😚
😀  Done Building Distance Matrix 😀 !
😚  Begin Identifying Sample Barycenters  😚
😀  Done Identifying Sample Barycenters 😀 !
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.


[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   2 out of   2 | elapsed:    4.1s remaining:    0.0s
[Parallel(n_jobs=4)]: Done   2 out of   2 | elapsed:    4.1s finished


Epoch 1/100
1/1 [==============================] - 0s 2ms/step - loss: 2.9937 - accuracy: 0.1500
Epoch 2/100
1/1 [==============================] - 0s 5ms/step - loss: 2.9854 - accuracy: 0.1000
Epoch 3/100
1/1 [==============================] - 0s 2ms/step - loss: 2.9774 - accuracy: 0.1000
Epoch 4/100
1/1 [==============================] - 0s 1ms/step - loss: 2.9697 - accuracy: 0.1000
Epoch 5/100
1/1 [==============================] - 0s 2ms/step - loss: 2.9622 - accuracy: 0.1000
Epoch 6/100
1/1 [==============================] - 0s 3ms/step - loss: 2.9550 - accuracy: 0.1000
Epoch 7/100
1/1 [==============================] - 0s 3ms/step - loss: 2.9479 - accuracy: 0.1000
Epoch 8/100
1/1 [==============================] - 0s 2ms/step - loss: 2.9408 - accuracy: 0.1000
Epoch 9/100
1/1 [==============================] - 0s 2ms/step - loss: 2.9335 - accuracy: 0.1000
Epoch 10/100
1/1 [==============================] - 0s 2ms/step - loss: 2.9262 - accuracy: 0.1000
Epoch 11/100
1/1 [===========

1/1 [==============================] - 0s 1ms/step - loss: 2.0917 - accuracy: 0.3000
Epoch 85/100
1/1 [==============================] - 0s 3ms/step - loss: 2.0819 - accuracy: 0.3000
Epoch 86/100
1/1 [==============================] - 0s 4ms/step - loss: 2.0721 - accuracy: 0.3000
Epoch 87/100
1/1 [==============================] - 0s 3ms/step - loss: 2.0622 - accuracy: 0.3000
Epoch 88/100
1/1 [==============================] - 0s 2ms/step - loss: 2.0524 - accuracy: 0.3000
Epoch 89/100
1/1 [==============================] - 0s 1ms/step - loss: 2.0424 - accuracy: 0.3000
Epoch 90/100
1/1 [==============================] - 0s 3ms/step - loss: 2.0323 - accuracy: 0.3000
Epoch 91/100
1/1 [==============================] - 0s 1ms/step - loss: 2.0222 - accuracy: 0.3000
Epoch 92/100
1/1 [==============================] - 0s 1ms/step - loss: 2.0121 - accuracy: 0.3500
Epoch 93/100
1/1 [==============================] - 0s 2ms/step - loss: 2.0019 - accuracy: 0.3500
Epoch 94/100
1/1 [===============

100%|██████████| 14/14 [00:00<00:00, 975.08it/s]

#---------------------------------------#
Building Training Set (Regression): START
#---------------------------------------#
#-------------------------------------#
Building Training Set (Regression): END
#-------------------------------------#
#-------------------------------------#
Building Test Set (Predictions): START
#-------------------------------------#
#-----------------------------------#
Building Test Set (Predictions): END
#-----------------------------------#
#-----------------------------#
Building Barycenters Set: START
#-----------------------------#
#-----------------------------#
Building Barycenters Set: END
#-----------------------------#
Building Training Set Performance Metrics
               W1  E[X']-E[X]  (E[X'^2]-E[X^2])^.5  (E[X'^3]-E[X^3])^(1/3)  \
MAE  1.935638e-05    0.002554         2.553679e-09                0.009252   
MSE  5.189960e-10    0.000009         1.434493e-17                0.000095   

     (E[X'^4]-E[X^4])^.25  
MAE              0.015228  

---